[theme]
base = "light"
primaryColor = "#0E766E"
backgroundColor = "#F7F9FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#14283F"
font = "sans serif"
[server]
headless = true
[browser]
gatherUsageStats = false
